### PR TITLE
Use sourceContents when non-null, even if it's an empty string

### PR DESCRIPTION
**Pull request by bshepherdson**
When using an optimizing compiler, it may be that all the functions in a
file have been inlined into their call sites, leaving the file empty.
But there are still references to that file in other modules, whose source
maps will contain `sources` and `sourceContents` entries for the empty file.

The `sourceContents` for the empty files is `""`, the empty string.
That's falsy in JavaScript which causes this check to wrongly fail,
leading to an attempt to open the formerly empty but now missing file,
breaking compilation.

This tweaks the check to allow an empty but non-`null` `sourceContents`.

**Background:**

In my case the optimizing compiler in question is a ClojureScript compiler
https://github.com/thheller/shadow-cljs, which wraps the Google Closure compiler.
The ClojureScript code is used as a library by our JS and TS code, and this issue
is blocking getting source maps working for optimized release builds.

### CODE REVIEW

**Comment by uladzimirdev** [comment]
@7rulnik could you please take a look?

**Comment by 7rulnik** [comment]
@uladzimirdev @bshepherdson Sorry guys, I was super busy during the last weeks.

I am away from my laptop for now. I will try to release it this or next week!
Don't hesitate to ping me next week if I forget

**Comment by bshepherdson** [comment]
Awesome, thanks! @7rulnik are you planning to cut a release with this change?

**Comment by 7rulnik** [comment]
I was thinking about solving https://github.com/7rulnik/source-map-js/issues/18 too within the next release, but it feels like it's better to solve it independently. So I will make a release with this PR on Friday

**Comment by 7rulnik** [comment]
Better late than never…
https://github.com/7rulnik/source-map-js/releases/tag/v1.0.3

**Pull request merged**
