### PR TITLE
Reduce npm package size

### PR DESCRIPTION
**Pull request by ai**
This change reduces `source-map-js` footprint in `node_modules` from **700 KB** (!) to 100 KB.

Now, `source-map-js` is 77% of [installing size of PostCSS](https://packagephobia.com/result?p=postcss) 😓.

* Remove `dist/` with webpack pre-build. Use case for pre-build is very limited and can be easily replaced by `webpack` on user’s side. For instance, most of my open source doesn’t have pre-build files.
* Remove long API docs from `README.md` in npm package by `clean-publish`. You will to release this package with `npx clean-publish` instead of `npm publish`

Also https://github.com/7rulnik/source-map-js/pull/6 can be merged to fix now useless `package.json` key,

### CODE REVIEW

**Comment by 7rulnik** [comment]
@ai sorry for slow response

I think we should keep webpack, because currently, it is necessary for benchmarking in a browsers.
Also, we can remove API documentation and replace it with link to original source-map documentation.

And I like the idea of removing comments from published code. If you think it's safe enough, so let's do it.

**Comment by 7rulnik** [comment]
And as I understand, it should be major release? I'm fine with it. We can release it as 1.0.0 BTW. I thought that it will be useful to try keep in sync versions with original source-map, but seems that it doesn't make any sense.

**Comment by ai** [comment]
> I think we should keep webpack, because currently, it is necessary for benchmarking in a browsers.

Can we build webpack version just to use in benchmark and do not put file to npm package?

**Comment by ai** [comment]
> And as I understand, it should be major release

Yeap, let’s do major (1.0 or 0.7).

**Comment by ai** [comment]
😍

**Pull request merged**
