### PR TITLE
Ensure null source is respected.

### LINKED ISSUE #25: mapping.source is not null even if the original is.
When trying to create a source map generator form a consumer that has mappings with just the generated position we get an error.

## Code to reproduce:

```ts
import { SourceMapGenerator, SourceMapConsumer } from 'source-map-js';

const original = new SourceMapGenerator({
    file: "origina.min.js",
})
original.addMapping({
    generated: { line: 1, column: 1},
    original: null!,
    source: null!,
});

const consumer = new SourceMapConsumer(original.toJSON());

const fromConsumer = SourceMapGenerator.fromSourceMap(consumer);
```

## Actual result 

Error: `original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.`

## Expected result

We should be able to create a source map generator from a consumer that has mappings with only generated position.

## Cause 

When mappings are produced they get a `source` even if they did not originally have one. [Code](https://github.com/7rulnik/source-map-js/blob/9b69fab7227431b5973ce65d3f7a38c85cfdbc75/lib/source-map-consumer.js#L151)

```js

      var mapping = mappings[i];
      var source = mapping.source === null ? null : sources.at(mapping.source);
      source = util.computeSourceURL(sourceRoot, source, sourceMapURL); 

```

`util.computeSourceURL` will return `.` if all components are null.

### PR DESCRIPTION
**Pull request by dragomirtitian**
Fixes #25

### CODE REVIEW

**Comment by 7rulnik** [comment]
@dragomirtitian could you revert yarn.lock change?

@ai what do you think? Asking because PostCSS is the largest project that uses source-map-js and we had problems with this issue before

**Comment by ai** [comment]
LGTM

**Comment by 7rulnik** [comment]
Thanks for PR and sorry for waiting!
Published as https://www.npmjs.com/package/source-map-js/v/1.2.1

**Comment by dragomirtitian** [comment]
Than you for the publish :)

**Pull request merged**
