### PR TITLE
Improve ts declarations 

### LINKED ISSUE #12: Type declarations are not null-safe
For instance, `SourceMapConsumer#sourceContentFor` returns `string|null`, not `string` as declared in source-map.d.ts.

### PR DESCRIPTION
**Pull request by dragomirtitian**
Fixes #12. Also other general improvements.

### CODE REVIEW

**Comment by andersk** [comment]
Consider rebasing this onto #16. (They currently conflict because #16 dedents everything to remove the incorrect `declare module` wrapper.)

**Comment by dragomirtitian** [comment]
@andersk  Sure I can do that. But do these PR have a path to being merged? #16 has been quiet for a half a year. Is @7rulnik still actively maintaining this project? I ask because we are looking at adopting this but #25 is really a show stopper since we have to reimplement `fromSourceMap` which is technically doable but worrying.

**Comment by 7rulnik** [comment]
@dragomirtitian hi! Well, I guess we need to define «actively».

At the start of the fork, I did not expect any further contributions other than those described in the @mraleph blog post.

But as we can see there is a demand for it. For now, this project has 29kk installs a week which is pretty huge. Because of this I kinda worried about change that I don't have time to test by myself or don't have experience to judge it.

Despite all of the above, I am open to merging this and other pull requests.

**Comment by dragomirtitian** [comment]
@7rulnik That is great to hear. For sure I get the reluctance to make any big changes, and objectively there probably is no need. If it works why fix it :)

**Comment by 7rulnik** [comment]
I rebased it onto #16

**Comment by 7rulnik** [comment]
Thanks for PR and sorry for waiting!
Published as https://www.npmjs.com/package/source-map-js/v/1.2.1

**Pull request merged**
